### PR TITLE
Fix reserve key words issue in persist-tools

### LINKED ISSUE #8531: Invalid Model Generation from Persist Tool When Using Reserved Words
### Area

None

### Description

When generating models using the persist tool, errors occur if a type or field name conflicts with a Ballerina reserved word.

Note the class field here
```bal
@sql:Name {value: "enrollments"}
public type Enrollment record {|
    @sql:Generated
    readonly int id;
    @sql:Name {value: "student_id"}
    @sql:Index {name: "student_id"}
    int studentId;
    @sql:Name {value: "class_id"}
    @sql:Index {name: "class_id"}
    int classId;
    @sql:Name {value: "enrolled_on"}
    time:Date? enrolledOn;
    @sql:Relation {keys: ["studentId"]}
    Student student;
    @sql:Relation {keys: ["classId"]}
    Class class;
|};
```

### Steps to Reproduce

1. Create a database schema with a table named class.
2. Create another table that has a relation to the class table.
3. Generate the persist client and models using the persist tool.

### Version

Persist tool 1.8.0
Ballerina SwanLake Update 13

### Environment Details (with versions)

_No response_

### PR DESCRIPTION
**Pull request by daneshk**
## Purpose

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/8531

## Problem

When a database table or relation field name matched a Ballerina reserved keyword (e.g., `class`), the `persist generate` and `persist pull` commands produced invalid Ballerina code — for example:

```ballerina
// Invalid — 'class' is a reserved keyword
Class class;

// Expected — escaped with single-quote prefix
Class 'class;
```

The escaping mechanism in `EntityField.Builder` was already correct. The bug was solely that the keyword check in `StubUtils.isLiteralName()` used a hardcoded list that was out of sync with Ballerina Swan Lake — missing `class` and 20 other current keywords.

---

### `StubUtils.java`

Replaced the 115-entry hardcoded `String[]` with a dynamic `Set<String>` derived directly from the Ballerina compiler's `SyntaxKind` enum:

```java
private static final Set<String> BALLERINA_KEYWORDS = Arrays.stream(SyntaxKind.values())
        .filter(kind -> kind.name().endsWith("_KEYWORD"))
        .map(kind -> AbstractNodeFactory.createToken(kind).text())
        .collect(Collectors.toSet());
```

`AbstractNodeFactory` was already a compile-time dependency. This approach stays in sync automatically with the `ballerina-parser` version used by the project.

---

## Files Changed

| File | Change |
|---|---|
| `persist-core/src/main/java/io/ballerina/persist/utils/StubUtils.java` | Replace hardcoded keyword list with `SyntaxKind`-derived set |
| `persist-cli-tests/src/test/java/io/ballerina/persist/tools/ToolingGenerateTest.java` | Add test #126 `testGenerateWithReservedWordClass()` |
| `persist-core/src/test/java/io/ballerina/persist/utils/StubUtilsTest.java` | New unit test for `isLiteralName()` |
| `test-src/input/tool_test_generate_126_reserved_words/` | New test input: `Class`/`Enrollment` model using `'class` field |
| `test-src/output/tool_test_generate_126_reserved_words/` | Expected generated output: `persist_types.bal`, `persist_client.bal`, `script.sql`, `Persist.toml` |

---

## Keyword Comparison: Old Hardcoded List vs. SyntaxKind-derived List

**Old list:** 115 entries (1 duplicate `error`) | **SyntaxKind list:** 103 entries | **In common:** 82

### 33 words in OLD list but NOT in SyntaxKind

These are stale Ballerina 1.x keywords removed in Swan Lake. They were being unnecessarily escaped and are no longer reserved:

| | | | |
|---|---|---|---|
| `abort` | `aborted` | `all` | `but` |
| `catch` | `channel` | `committed` | `default` |
| `every` | `finally` | `followed` | `for` |
| `forever` | `full` | `having` | `init` |
| `inner` | `left` | `onretry` | `primarykey` |
| `retries` | `right` | `snapshot` | `some` |
| `throw` | `transformer` | `try` | `unidirectional` |
| `untaint` | `version` | `window` | `with` |
| `within` | | | |

### 21 words in SyntaxKind but NOT in OLD list

These are current Swan Lake keywords that were **missing** from the old list — they could cause incorrect code generation if used as entity/field names:

| | | | |
|---|---|---|---|
| `class` | `do` | `null` | `true` |
| `false` | `fail` | `let` | `key` |
| `select` | `commit` | `rollback` | `transactional` |
| `collect` | `conflict` | `equals` | `natural` |
| `field` | `re` | `base16` | `base64` |
| `_` | `!is` | | |

### 82 keywords present in both lists

These were correctly handled before and after the fix:

`annotation`, `anydata`, `boolean`, `byte`, `check`, `checkpanic`, `client`, `conflict`,
`const`, `decimal`, `else`, `enum`, `error`, `external`, `final`, `float`,
`flush`, `fork`, `function`, `future`, `handle`, `if`, `import`, `in`,
`int`, `is`, `isolated`, `join`, `json`, `limit`, `listener`, `lock`,
`map`, `match`, `never`, `new`, `object`, `on`, `order`, `outer`,
`panic`, `parameter`, `public`, `readonly`, `record`, `remote`, `resource`, `returns`,
`service`, `start`, `stream`, `string`, `table`, `transaction`, `trap`, `type`,
`typeof`, `var`, `where`, `while`, `worker`, `xml`, `xmlns`, `configurable`,
`distinct`, `from`, `private`, `return`, `typedesc`, `readonly`, `wait`, `check`,
`foreach`, `module`, `limit`, `on`, `in`, `outer`, `join`

## Checklist
- [x] Linked to an issue
- ~[ ] Updated the specification~
- [x] Updated the changelog
- [x] Added tests

This pull request fixes incorrect code generation when database tables or fields use identifiers that collide with Ballerina reserved keywords. The persist tooling now derives the language keyword list from the Ballerina compiler’s SyntaxKind enum instead of using a stale hardcoded list, ensuring keyword detection stays in sync with the compiler and preventing generation of invalid Ballerina code.

Key changes
- Core fix
  - persist-core/src/main/java/io/ballerina/persist/utils/StubUtils.java: Replaced the hardcoded reserved-name array with a dynamically built Set<String> derived from SyntaxKind values ending with _KEYWORD and updated isLiteralName() to use set membership.
- Tests and fixtures
  - Added unit tests: persist-core/src/test/java/io/ballerina/persist/utils/StubUtilsTest.java to validate reserved vs non-reserved word detection.
  - Added integration test: persist-cli-tests/src/test/java/io/ballerina/persist/tools/ToolingGenerateTest.java (testGenerateWithReservedWordClass) and corresponding input/output fixtures under persist-cli-tests/src/test/resources/test-src/input/... and .../output/... to verify generation when an entity/field is named "class" (covering generated types, client, and SQL).
  - Adjusted other test expectations and corrected several generated test outputs related to metadata keys and quoted field names.
- Documentation
  - Updated changelog.md with an Unreleased entry describing the fix.
- Misc
  - Minor .gitignore correction for test resource paths.

Outcome
- Persist tooling now reliably detects Ballerina reserved keywords in line with the compiler, emits properly escaped identifiers (e.g., 'class), and avoids producing invalid generated code. Unit and integration tests ensure the detection logic and end-to-end generation for reserved-word scenarios are covered.

### CODE REVIEW

File: persist-core/src/test/java/io/ballerina/persist/utils/StubUtilsTest.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
+/*
+ *  Copyright (c) 2025 WSO2 LLC. (http://www.wso2.com).
```
Comment (ayeshLK) [inline persist-core/src/test/java/io/ballerina/persist/utils/StubUtilsTest.java]:
```suggestion
 *  Copyright (c) 2026 WSO2 LLC. (http://www.wso2.com).
```

File: persist-core/src/main/java/io/ballerina/persist/utils/StubUtils.java [hunk 2]
```diff
@@ -26,25 +33,16 @@ public class StubUtils {
...
-            "typedesc", "type", "future", "anydata", "handle", "var", "new", "init", "if", "match", "else",
-            "foreach", "while", "continue", "break", "fork", "join", "some", "all", "try", "catch", "finally", "throw",
-            "panic", "trap", "return", "transaction", "abort", "retry", "onretry", "retries", "committed", "aborted",
-            "with", "in", "lock", "untaint", "start", "but", "check", "checkpanic", "primarykey", "is", "flush",
-            "wait", "default", "enum", "error"};
+    /**
+     * Set of Ballerina reserved keywords derived directly from the compiler's SyntaxKind enum.
+     * This stays in sync with the Ballerina parser version used by the project.
+     */
+    private static final Set<String> BALLERINA_KEYWORDS = Arrays.stream(SyntaxKind.values())
```
Comment (TharmiganK) [inline persist-core/src/main/java/io/ballerina/persist/utils/StubUtils.java]: Can't we get all the key words from this compiler API?
```
public static final List<String> BAL_KEYWORDS = SyntaxInfo.keywords();
```

Comment (daneshk) [reply persist-core/src/main/java/io/ballerina/persist/utils/StubUtils.java]: Fixed in [135d27f](https://github.com/ballerina-platform/persist-tools/pull/446/commits/135d27fc79492a25e33c2d33b58bce68141f2a2c)

**Review by TharmiganK — APPROVED** [review]
LGTM
